### ISSUE TITLE
Store db connections in local storage

### ISSUE THREAD

**Issue by juancarlosllhL** [antoniovizuete/clickhouser#68]
I would like to be able to save the connections locally in the browser.

The application could include a button to save a connection (by naming it) and a dropdown where you can load the data of a saved connection.

The connections would be saved in the browser using local storage.

**Comment by antoniovizuete** [comment]
I'm close to finishing the request.

Before releasing it, I have to add a way to encrypt the connections' passwords because they are currently stored on local storage as plain text. It could be very harmful.
